/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 52
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__headers_token1 = 1,
  anon_sym_SPACE = 2,
  sym_header_separator = 3,
  sym_header_field = 4,
  anon_sym_From = 5,
  anon_sym_To = 6,
  anon_sym_Cc = 7,
  anon_sym_Bcc = 8,
  anon_sym_Reply_DASHTo = 9,
  sym_header_field_subject = 10,
  aux_sym_header_unstructured_token1 = 11,
  sym_atom = 12,
  sym_quoted_string = 13,
  anon_sym_GT = 14,
  anon_sym_LT = 15,
  sym_email_address = 16,
  sym_body_signature_separator = 17,
  sym_quote_contents = 18,
  aux_sym__body_line_token1 = 19,
  sym_source_file = 20,
  aux_sym__headers = 21,
  sym__header = 22,
  sym_header_email = 23,
  sym_header_other = 24,
  sym_header_subject = 25,
  sym_header_field_email = 26,
  sym_header_unstructured = 27,
  sym_subject = 28,
  sym_atom_block = 29,
  sym_email_delimiter = 30,
  sym_email = 31,
  sym_body_signature = 32,
  sym_body_separator = 33,
  sym_body = 34,
  sym_quote_group = 35,
  sym_quoted_block = 36,
  sym__quoted_line = 37,
  sym_quote_marker = 38,
  sym_body_block = 39,
  sym__body_line = 40,
  sym__empty_line = 41,
  aux_sym_atom_block_repeat1 = 42,
  aux_sym_body_signature_repeat1 = 43,
  aux_sym_body_repeat1 = 44,
  aux_sym_quote_group_repeat1 = 45,
  aux_sym_body_block_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__headers_token1] = "_headers_token1",
  [anon_sym_SPACE] = " ",
  [sym_header_separator] = "header_separator",
  [sym_header_field] = "header_field",
  [anon_sym_From] = "From",
  [anon_sym_To] = "To",
  [anon_sym_Cc] = "Cc",
  [anon_sym_Bcc] = "Bcc",
  [anon_sym_Reply_DASHTo] = "Reply-To",
  [sym_header_field_subject] = "header_field_subject",
  [aux_sym_header_unstructured_token1] = "header_unstructured_token1",
  [sym_atom] = "atom",
  [sym_quoted_string] = "quoted_string",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [sym_email_address] = "email_address",
  [sym_body_signature_separator] = "body_signature_separator",
  [sym_quote_contents] = "quote_contents",
  [aux_sym__body_line_token1] = "_body_line_token1",
  [sym_source_file] = "source_file",
  [aux_sym__headers] = "_headers",
  [sym__header] = "_header",
  [sym_header_email] = "header_email",
  [sym_header_other] = "header_other",
  [sym_header_subject] = "header_subject",
  [sym_header_field_email] = "header_field_email",
  [sym_header_unstructured] = "header_unstructured",
  [sym_subject] = "subject",
  [sym_atom_block] = "atom_block",
  [sym_email_delimiter] = "email_delimiter",
  [sym_email] = "email",
  [sym_body_signature] = "body_signature",
  [sym_body_separator] = "body_separator",
  [sym_body] = "body",
  [sym_quote_group] = "quote_group",
  [sym_quoted_block] = "quoted_block",
  [sym__quoted_line] = "_quoted_line",
  [sym_quote_marker] = "quote_marker",
  [sym_body_block] = "body_block",
  [sym__body_line] = "_body_line",
  [sym__empty_line] = "_empty_line",
  [aux_sym_atom_block_repeat1] = "atom_block_repeat1",
  [aux_sym_body_signature_repeat1] = "body_signature_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_quote_group_repeat1] = "quote_group_repeat1",
  [aux_sym_body_block_repeat1] = "body_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__headers_token1] = aux_sym__headers_token1,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_header_separator] = sym_header_separator,
  [sym_header_field] = sym_header_field,
  [anon_sym_From] = anon_sym_From,
  [anon_sym_To] = anon_sym_To,
  [anon_sym_Cc] = anon_sym_Cc,
  [anon_sym_Bcc] = anon_sym_Bcc,
  [anon_sym_Reply_DASHTo] = anon_sym_Reply_DASHTo,
  [sym_header_field_subject] = sym_header_field_subject,
  [aux_sym_header_unstructured_token1] = aux_sym_header_unstructured_token1,
  [sym_atom] = sym_atom,
  [sym_quoted_string] = sym_quoted_string,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [sym_email_address] = sym_email_address,
  [sym_body_signature_separator] = sym_body_signature_separator,
  [sym_quote_contents] = sym_quote_contents,
  [aux_sym__body_line_token1] = aux_sym__body_line_token1,
  [sym_source_file] = sym_source_file,
  [aux_sym__headers] = aux_sym__headers,
  [sym__header] = sym__header,
  [sym_header_email] = sym_header_email,
  [sym_header_other] = sym_header_other,
  [sym_header_subject] = sym_header_subject,
  [sym_header_field_email] = sym_header_field_email,
  [sym_header_unstructured] = sym_header_unstructured,
  [sym_subject] = sym_subject,
  [sym_atom_block] = sym_atom_block,
  [sym_email_delimiter] = sym_email_delimiter,
  [sym_email] = sym_email,
  [sym_body_signature] = sym_body_signature,
  [sym_body_separator] = sym_body_separator,
  [sym_body] = sym_body,
  [sym_quote_group] = sym_quote_group,
  [sym_quoted_block] = sym_quoted_block,
  [sym__quoted_line] = sym__quoted_line,
  [sym_quote_marker] = sym_quote_marker,
  [sym_body_block] = sym_body_block,
  [sym__body_line] = sym__body_line,
  [sym__empty_line] = sym__empty_line,
  [aux_sym_atom_block_repeat1] = aux_sym_atom_block_repeat1,
  [aux_sym_body_signature_repeat1] = aux_sym_body_signature_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_quote_group_repeat1] = aux_sym_quote_group_repeat1,
  [aux_sym_body_block_repeat1] = aux_sym_body_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__headers_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_header_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_From] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_To] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Cc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bcc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Reply_DASHTo] = {
    .visible = true,
    .named = false,
  },
  [sym_header_field_subject] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_unstructured_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_email_address] = {
    .visible = true,
    .named = true,
  },
  [sym_body_signature_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_contents] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__body_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__headers] = {
    .visible = false,
    .named = false,
  },
  [sym__header] = {
    .visible = false,
    .named = true,
  },
  [sym_header_email] = {
    .visible = true,
    .named = true,
  },
  [sym_header_other] = {
    .visible = true,
    .named = true,
  },
  [sym_header_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field_email] = {
    .visible = true,
    .named = true,
  },
  [sym_header_unstructured] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_block] = {
    .visible = true,
    .named = true,
  },
  [sym_email_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_email] = {
    .visible = true,
    .named = true,
  },
  [sym_body_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_body_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_block] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_line] = {
    .visible = false,
    .named = true,
  },
  [sym_quote_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_body_block] = {
    .visible = true,
    .named = true,
  },
  [sym__body_line] = {
    .visible = false,
    .named = true,
  },
  [sym__empty_line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_atom_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_signature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 31,
  [51] = 51,
};

static const TSCharacterRange sym_atom_character_set_1[] = {
  {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', '-'}, {'/', '9'}, {'=', '='}, {'?', '?'}, {'A', 'Z'},
  {'^', '~'}, {0x80, 0x10ffff},
};

static const TSCharacterRange sym_email_address_character_set_1[] = {
  {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', '-'}, {'/', '9'}, {'=', '='}, {'?', '?'}, {'A', 'Z'},
  {'^', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(50);
      ADVANCE_MAP(
        '\n', 51,
        '\r', 1,
        ' ', 53,
        '"', 4,
        ':', 57,
        '<', 121,
        '>', 120,
        'B', 102,
        'C', 99,
        'F', 112,
        'R', 103,
        'S', 114,
        'T', 108,
      );
      if (('!' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('=' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(53);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '<') ADVANCE(121);
      if (lookahead == '>') ADVANCE(120);
      if (('!' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('=' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(46);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(46);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\n' || '\f' < lookahead)) ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(119);
      if (lookahead == '\\') ADVANCE(46);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\n' || '\f' < lookahead)) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '.') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '0') ADVANCE(15);
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '2') ADVANCE(11);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '5') ADVANCE(12);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == ']') ADVANCE(122);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == ']') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(15);
      if (('6' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == ']') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == ']') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == ']') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == ':') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '-') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '.') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '5') ADVANCE(21);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == '.') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '5') ADVANCE(26);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(27);
      END_STATE();
    case 26:
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == '.') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '5') ADVANCE(31);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == '.') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead == '.') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == '.') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 34:
      if (lookahead == '0') ADVANCE(29);
      if (lookahead == '1') ADVANCE(33);
      if (lookahead == '2') ADVANCE(30);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == '0') ADVANCE(19);
      if (lookahead == '1') ADVANCE(23);
      if (lookahead == '2') ADVANCE(20);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 36:
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == '1') ADVANCE(28);
      if (lookahead == '2') ADVANCE(25);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 37:
      if (lookahead == '@') ADVANCE(38);
      END_STATE();
    case 38:
      if (lookahead == '[') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 39:
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead == ']') ADVANCE(124);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(39);
      END_STATE();
    case 40:
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead == ']') ADVANCE(124);
      if ((0x01 <= lookahead && lookahead <= '\t') ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x7f)) ADVANCE(39);
      END_STATE();
    case 41:
      if (lookahead == '\\') ADVANCE(40);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(39);
      END_STATE();
    case 42:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      END_STATE();
    case 43:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(94);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 45:
      if (set_contains(sym_email_address_character_set_1, 9, lookahead)) ADVANCE(18);
      END_STATE();
    case 46:
      if ((0x01 <= lookahead && lookahead <= '\t') ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x7f)) ADVANCE(3);
      END_STATE();
    case 47:
      if (eof) ADVANCE(50);
      ADVANCE_MAP(
        '\n', 51,
        '\r', 1,
        ' ', 53,
        'B', 64,
        'C', 61,
        'F', 74,
        'R', 65,
        'S', 76,
        'T', 70,
      );
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 48:
      if (eof) ADVANCE(50);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(56);
      if (lookahead == '-') ADVANCE(131);
      if (lookahead == '>') ADVANCE(120);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 49:
      if (eof) ADVANCE(50);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(56);
      if (lookahead == '>') ADVANCE(120);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym__headers_token1);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym__headers_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '\r') ADVANCE(94);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(127);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_header_separator);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == '-') ADVANCE(59);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'T') ADVANCE(72);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'b') ADVANCE(67);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(84);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(86);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(75);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(62);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'e') ADVANCE(63);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'j') ADVANCE(66);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'l') ADVANCE(77);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'm') ADVANCE(80);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(82);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(69);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(88);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'p') ADVANCE(68);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'r') ADVANCE(71);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 't') ADVANCE(90);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'u') ADVANCE(60);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'y') ADVANCE(58);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_From);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_From);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_To);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_To);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_Cc);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_Cc);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_Bcc);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_Bcc);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_Reply_DASHTo);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_Reply_DASHTo);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_header_field_subject);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_header_field_subject);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(78);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == ' ') ADVANCE(54);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '\r') ADVANCE(94);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '\r') ADVANCE(94);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '\r') ADVANCE(94);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(94);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '-') ADVANCE(97);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('/' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'T') ADVANCE(110);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'b') ADVANCE(105);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'c') ADVANCE(83);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'c') ADVANCE(85);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'c') ADVANCE(113);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'c') ADVANCE(100);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'e') ADVANCE(111);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'e') ADVANCE(101);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'j') ADVANCE(104);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'l') ADVANCE(115);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'm') ADVANCE(79);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'o') ADVANCE(81);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'o') ADVANCE(107);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'o') ADVANCE(87);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'p') ADVANCE(106);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'r') ADVANCE(109);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 't') ADVANCE(89);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'u') ADVANCE(98);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == 'y') ADVANCE(96);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(116);
      if (lookahead > 0x7f) ADVANCE(117);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_atom);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_quoted_string);
      if (lookahead == '@') ADVANCE(38);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_email_address);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_email_address);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '.') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_email_address);
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead == ']') ADVANCE(124);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(39);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_body_signature_separator);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_quote_contents);
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(127);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_quote_contents);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == '\n') ADVANCE(125);
      if (lookahead == '\r') ADVANCE(129);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == '\n') ADVANCE(125);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == ' ') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == '-') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 47},
  [2] = {.lex_state = 47},
  [3] = {.lex_state = 47},
  [4] = {.lex_state = 48},
  [5] = {.lex_state = 48},
  [6] = {.lex_state = 49},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 48},
  [9] = {.lex_state = 47},
  [10] = {.lex_state = 48},
  [11] = {.lex_state = 48},
  [12] = {.lex_state = 48},
  [13] = {.lex_state = 49},
  [14] = {.lex_state = 49},
  [15] = {.lex_state = 49},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 48},
  [19] = {.lex_state = 48},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 49},
  [22] = {.lex_state = 91},
  [23] = {.lex_state = 49},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 95},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 126},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 126},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__headers_token1] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(3),
    [sym_header_separator] = ACTIONS(1),
    [anon_sym_From] = ACTIONS(1),
    [anon_sym_To] = ACTIONS(1),
    [anon_sym_Cc] = ACTIONS(1),
    [anon_sym_Bcc] = ACTIONS(1),
    [anon_sym_Reply_DASHTo] = ACTIONS(1),
    [sym_header_field_subject] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [sym_email_address] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(41),
    [aux_sym__headers] = STATE(2),
    [sym__header] = STATE(46),
    [sym_header_email] = STATE(46),
    [sym_header_other] = STATE(46),
    [sym_header_subject] = STATE(46),
    [sym_header_field_email] = STATE(35),
    [anon_sym_SPACE] = ACTIONS(3),
    [sym_header_field] = ACTIONS(5),
    [anon_sym_From] = ACTIONS(7),
    [anon_sym_To] = ACTIONS(7),
    [anon_sym_Cc] = ACTIONS(7),
    [anon_sym_Bcc] = ACTIONS(7),
    [anon_sym_Reply_DASHTo] = ACTIONS(7),
    [sym_header_field_subject] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(5), 1,
      sym_header_field,
    ACTIONS(9), 1,
      sym_header_field_subject,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym__headers_token1,
    STATE(3), 1,
      aux_sym__headers,
    STATE(6), 1,
      sym_body_separator,
    STATE(35), 1,
      sym_header_field_email,
    STATE(46), 4,
      sym__header,
      sym_header_email,
      sym_header_other,
      sym_header_subject,
    ACTIONS(7), 5,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
  [38] = 8,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(17), 1,
      sym_header_field,
    ACTIONS(23), 1,
      sym_header_field_subject,
    STATE(3), 1,
      aux_sym__headers,
    STATE(35), 1,
      sym_header_field_email,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
    STATE(46), 4,
      sym__header,
      sym_header_email,
      sym_header_other,
      sym_header_subject,
    ACTIONS(20), 5,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
  [71] = 11,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      aux_sym__headers_token1,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(32), 1,
      anon_sym_GT,
    ACTIONS(34), 1,
      sym_body_signature_separator,
    ACTIONS(36), 1,
      aux_sym__body_line_token1,
    STATE(37), 1,
      sym_quoted_block,
    STATE(39), 1,
      sym_quote_marker,
    STATE(8), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    STATE(11), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(5), 4,
      sym_quote_group,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [110] = 10,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(40), 1,
      aux_sym__headers_token1,
    ACTIONS(43), 1,
      anon_sym_GT,
    ACTIONS(46), 1,
      aux_sym__body_line_token1,
    STATE(37), 1,
      sym_quoted_block,
    STATE(39), 1,
      sym_quote_marker,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      sym_body_signature_separator,
    STATE(8), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    STATE(11), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(5), 4,
      sym_quote_group,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [147] = 10,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(32), 1,
      anon_sym_GT,
    ACTIONS(36), 1,
      aux_sym__body_line_token1,
    ACTIONS(49), 1,
      aux_sym__headers_token1,
    STATE(36), 1,
      sym_body,
    STATE(37), 1,
      sym_quoted_block,
    STATE(39), 1,
      sym_quote_marker,
    STATE(8), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    STATE(11), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(4), 4,
      sym_quote_group,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [183] = 9,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(51), 1,
      aux_sym__headers_token1,
    ACTIONS(57), 1,
      sym_email_address,
    STATE(16), 1,
      aux_sym_atom_block_repeat1,
    STATE(20), 1,
      sym_atom_block,
    STATE(38), 1,
      sym_email,
    STATE(40), 1,
      sym_email_delimiter,
    ACTIONS(53), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(55), 2,
      anon_sym_GT,
      anon_sym_LT,
  [213] = 7,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(32), 1,
      anon_sym_GT,
    ACTIONS(61), 1,
      aux_sym__body_line_token1,
    STATE(37), 1,
      sym_quoted_block,
    STATE(39), 1,
      sym_quote_marker,
    STATE(10), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      sym_body_signature_separator,
  [238] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
    ACTIONS(63), 7,
      sym_header_field,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
      sym_header_field_subject,
  [255] = 7,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(67), 1,
      anon_sym_GT,
    ACTIONS(70), 1,
      aux_sym__body_line_token1,
    STATE(37), 1,
      sym_quoted_block,
    STATE(39), 1,
      sym_quote_marker,
    STATE(10), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      sym_body_signature_separator,
  [280] = 4,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(36), 1,
      aux_sym__body_line_token1,
    STATE(12), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    ACTIONS(72), 4,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      anon_sym_GT,
      sym_body_signature_separator,
  [297] = 4,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(76), 1,
      aux_sym__body_line_token1,
    STATE(12), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      anon_sym_GT,
      sym_body_signature_separator,
  [314] = 5,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(79), 1,
      aux_sym__headers_token1,
    ACTIONS(81), 1,
      aux_sym__body_line_token1,
    STATE(42), 1,
      sym_body_signature,
    STATE(14), 3,
      sym__body_line,
      sym__empty_line,
      aux_sym_body_signature_repeat1,
  [332] = 5,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(81), 1,
      aux_sym__body_line_token1,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      aux_sym__headers_token1,
    STATE(15), 3,
      sym__body_line,
      sym__empty_line,
      aux_sym_body_signature_repeat1,
  [350] = 5,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      aux_sym__headers_token1,
    ACTIONS(92), 1,
      aux_sym__body_line_token1,
    STATE(15), 3,
      sym__body_line,
      sym__empty_line,
      aux_sym_body_signature_repeat1,
  [368] = 4,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    STATE(17), 1,
      aux_sym_atom_block_repeat1,
    ACTIONS(97), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(95), 3,
      aux_sym__headers_token1,
      anon_sym_GT,
      anon_sym_LT,
  [384] = 4,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    STATE(17), 1,
      aux_sym_atom_block_repeat1,
    ACTIONS(101), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(99), 3,
      aux_sym__headers_token1,
      anon_sym_GT,
      anon_sym_LT,
  [400] = 3,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      aux_sym__body_line_token1,
    ACTIONS(104), 4,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      anon_sym_GT,
      sym_body_signature_separator,
  [413] = 3,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(110), 1,
      aux_sym__body_line_token1,
    ACTIONS(108), 4,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      anon_sym_GT,
      sym_body_signature_separator,
  [426] = 5,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(112), 1,
      aux_sym__headers_token1,
    STATE(40), 1,
      sym_email_delimiter,
    STATE(44), 1,
      sym_email,
    ACTIONS(55), 2,
      anon_sym_GT,
      anon_sym_LT,
  [443] = 3,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(110), 1,
      aux_sym__body_line_token1,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
  [454] = 4,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(114), 1,
      aux_sym__headers_token1,
    ACTIONS(116), 1,
      aux_sym_header_unstructured_token1,
    STATE(49), 1,
      sym_header_unstructured,
  [467] = 3,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(120), 1,
      aux_sym__body_line_token1,
    ACTIONS(118), 2,
      aux_sym__headers_token1,
      anon_sym_GT,
  [478] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    STATE(48), 1,
      sym_email_delimiter,
    ACTIONS(55), 2,
      anon_sym_GT,
      anon_sym_LT,
  [489] = 3,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(122), 1,
      aux_sym_header_unstructured_token1,
    STATE(30), 1,
      sym_subject,
  [499] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(124), 2,
      aux_sym__headers_token1,
      sym_email_address,
  [507] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(126), 1,
      aux_sym__headers_token1,
  [514] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(128), 1,
      sym_header_separator,
  [521] = 2,
    ACTIONS(130), 1,
      aux_sym__headers_token1,
    ACTIONS(132), 1,
      anon_sym_SPACE,
  [528] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(134), 1,
      aux_sym__headers_token1,
  [535] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(136), 1,
      aux_sym__headers_token1,
  [542] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(138), 1,
      sym_header_separator,
  [549] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(140), 1,
      aux_sym__headers_token1,
  [556] = 2,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(142), 1,
      sym_quote_contents,
  [563] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(144), 1,
      sym_header_separator,
  [570] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
  [577] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(148), 1,
      aux_sym__headers_token1,
  [584] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(112), 1,
      aux_sym__headers_token1,
  [591] = 2,
    ACTIONS(30), 1,
      anon_sym_SPACE,
    ACTIONS(150), 1,
      sym_quote_contents,
  [598] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(152), 1,
      sym_email_address,
  [605] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
  [612] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [619] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(158), 1,
      sym_header_separator,
  [626] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(160), 1,
      aux_sym__headers_token1,
  [633] = 2,
    ACTIONS(162), 1,
      aux_sym__headers_token1,
    ACTIONS(164), 1,
      anon_sym_SPACE,
  [640] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(166), 1,
      aux_sym__headers_token1,
  [647] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(168), 1,
      aux_sym__headers_token1,
  [654] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(170), 1,
      aux_sym__headers_token1,
  [661] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(172), 1,
      aux_sym__headers_token1,
  [668] = 2,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(174), 1,
      aux_sym__headers_token1,
  [675] = 1,
    ACTIONS(176), 1,
      anon_sym_SPACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 71,
  [SMALL_STATE(5)] = 110,
  [SMALL_STATE(6)] = 147,
  [SMALL_STATE(7)] = 183,
  [SMALL_STATE(8)] = 213,
  [SMALL_STATE(9)] = 238,
  [SMALL_STATE(10)] = 255,
  [SMALL_STATE(11)] = 280,
  [SMALL_STATE(12)] = 297,
  [SMALL_STATE(13)] = 314,
  [SMALL_STATE(14)] = 332,
  [SMALL_STATE(15)] = 350,
  [SMALL_STATE(16)] = 368,
  [SMALL_STATE(17)] = 384,
  [SMALL_STATE(18)] = 400,
  [SMALL_STATE(19)] = 413,
  [SMALL_STATE(20)] = 426,
  [SMALL_STATE(21)] = 443,
  [SMALL_STATE(22)] = 454,
  [SMALL_STATE(23)] = 467,
  [SMALL_STATE(24)] = 478,
  [SMALL_STATE(25)] = 489,
  [SMALL_STATE(26)] = 499,
  [SMALL_STATE(27)] = 507,
  [SMALL_STATE(28)] = 514,
  [SMALL_STATE(29)] = 521,
  [SMALL_STATE(30)] = 528,
  [SMALL_STATE(31)] = 535,
  [SMALL_STATE(32)] = 542,
  [SMALL_STATE(33)] = 549,
  [SMALL_STATE(34)] = 556,
  [SMALL_STATE(35)] = 563,
  [SMALL_STATE(36)] = 570,
  [SMALL_STATE(37)] = 577,
  [SMALL_STATE(38)] = 584,
  [SMALL_STATE(39)] = 591,
  [SMALL_STATE(40)] = 598,
  [SMALL_STATE(41)] = 605,
  [SMALL_STATE(42)] = 612,
  [SMALL_STATE(43)] = 619,
  [SMALL_STATE(44)] = 626,
  [SMALL_STATE(45)] = 633,
  [SMALL_STATE(46)] = 640,
  [SMALL_STATE(47)] = 647,
  [SMALL_STATE(48)] = 654,
  [SMALL_STATE(49)] = 661,
  [SMALL_STATE(50)] = 668,
  [SMALL_STATE(51)] = 675,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__headers, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(43),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(32),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(28),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote_group, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote_group, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote_group_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_group_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote_group_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_signature, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_signature_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_signature_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_signature_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_block, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_atom_block_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_atom_block_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_line, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__quoted_line, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_line, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_line, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_other, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_separator, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_separator, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_email_delimiter, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_other, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_subject, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_field_email, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_block, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote_marker, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [154] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 5, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_unstructured, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_email, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_other, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mail(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
